### ISSUE TITLE
Any issues running in https?

### ISSUE THREAD

**Issue by goldbergjeffrey** [jbass86/winston-socket.io#1]
I realize I should test it first, but wondering if this will work over an https connection.  Have you tested?

**Comment by goldbergjeffrey** [comment]
ok, I tested.  I'm going to fork and alter for my needs.  Thanks for the head start.  Works like a charm with some tweaks!

**Comment by jbass86** [comment]
Sorry just saw this.  Yeah I would have assumed it should work fine over https.  If the tweaks you made are generic and you want to send me a merge request I can roll them into the mainline.
