### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by paveli** [jbass86/winston-socket.io#16]
Hi, can you please upgrade dependencies for this package? 
Currently, it depends on `socket.io-client` version 2 which is not working correctly with the latest version of `socket.io` server.

**Comment by jbass86** [comment]
Hey, yeah I can try to update it to socket.io 3 this week and push a new verion.

**Comment by jbass86** [comment]
> Hey, yeah I can try to update it to socket.io 3 this week and push a new verion.

I meant 4 (the latest)
