### ISSUE TITLE
winston.transports.SocketIO is not a constructor

### ISSUE THREAD

**Issue by aman750** [jbass86/winston-socket.io#4]
Gets a constructor error with the below code : 

 const winston = require('winston');
  require('winston-socket.io');
 

  let logger = winston.createLogger({
      transports: [

          new winston.transports.SocketIO({host: "mylocalhost" , port: 3000, log_topic:"abc", secure: true, reconnect: true})]
  });

node version : 10.16
winston : 3.0.0
![errorsocket](https://user-images.githubusercontent.com/29388156/60676212-f3dd5900-9e9b-11e9-9af8-0cc5b301a5bd.PNG)

**Comment by jbass86** [comment]
I just tested everything and it seems to be working alright on my end... Are you sure that you required it properly?  I updated the examples just now try pulling and running those.

**Comment by aman750** [comment]
> I just tested everything and it seems to be working alright on my end... Are you sure that you required it properly? I updated the examples just now try pulling and running those.

Is it working for node version > 8.x ?
