### ISSUE TITLE
winston-socket.io ignores metadata

### ISSUE THREAD

**Issue by paveli** [jbass86/winston-socket.io#8]
When I try to send log data together with some metadata object, winston-socket.io ignores it.

Example configuration:
```
exports.logger = winston.createLogger({
	format: format.combine(format.splat(), format.simple()),
	level: "info",
	transports: [
		new winston.transports.SocketIO({
			host: "http://localhost",
			port: 3001,
			secure: false,
			reconnect: true,
			namespace: "log",
			log_topic: "log"
		}),
		new winston.transports.Console()
	]
});
```

Log command:

`logger.info(msg, { myVar: myVal });`

Metadata will appear only in Console but will not be sent to SocketIO.
Is it possible to send metadata to SocketIO together with message?

**Comment by jbass86** [comment]
Hi, I am planning a 1.0 release of this transport where I will update it to support winston 3 and npm 2.  I will add support for metadata then as well.

**Comment by jbass86** [comment]
metadata works now.  Published a new version today.
